name: slpost
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^4.0.1
  font_awesome_flutter: ^10.4.0
  firebase_core:
  cloud_firestore: ^4.4.3
  velocity_x: ^3.6.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
      - assets/fitness_app/

