name: slpost
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  country_picker:
    git: https://github.com/vilakshan2996/flutter_country_picker.git
  cupertino_icons: ^1.0.2
  firebase_analytics: null
  firebase_core: ^2.7.1
  seo: ^0.0.2
  flutter:
    sdk: flutter
  flutter_svg: null
  font_awesome_flutter: ^10.4.0
  get: 4.6.5
  google_fonts: ^4.0.1
  lottie: ^2.2.0
  sidebarx: ^0.15.0
  velocity_x: ^3.6.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
