// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7FOPLHro37Q0YbzgKoix35LbnpodQMnk',
    appId: '1:886891249964:web:0e41c2a16c9e118dd6ac89',
    messagingSenderId: '886891249964',
    projectId: 'slpost-f8ac9',
    authDomain: 'slpost-f8ac9.firebaseapp.com',
    storageBucket: 'slpost-f8ac9.appspot.com',
    measurementId: 'G-GVZ0DN3TRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJVtR4KCONWZ2rIvUwYS8v7CQOhniZ-s',
    appId: '1:886891249964:android:2331b999cb96fce4d6ac89',
    messagingSenderId: '886891249964',
    projectId: 'slpost-f8ac9',
    storageBucket: 'slpost-f8ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2oIf57ltfvXR5qhIkstaxvjQzuSIrctk',
    appId: '1:886891249964:ios:347b0df4ed37f17cd6ac89',
    messagingSenderId: '886891249964',
    projectId: 'slpost-f8ac9',
    storageBucket: 'slpost-f8ac9.appspot.com',
    iosClientId: '886891249964-lutl8de7htl7d5r35eki7coog6a3rnfm.apps.googleusercontent.com',
    iosBundleId: 'lk.emtechmart.slpost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2oIf57ltfvXR5qhIkstaxvjQzuSIrctk',
    appId: '1:886891249964:ios:347b0df4ed37f17cd6ac89',
    messagingSenderId: '886891249964',
    projectId: 'slpost-f8ac9',
    storageBucket: 'slpost-f8ac9.appspot.com',
    iosClientId: '886891249964-lutl8de7htl7d5r35eki7coog6a3rnfm.apps.googleusercontent.com',
    iosBundleId: 'lk.emtechmart.slpost',
  );
}
